language: node_js
node_js:
  - "node"
  - "8"
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3


git:
  submodules: false
install:
    - npm install
test:
    - npm run test